### GENERAL SETTINGS ###

# Site settings
title: " "
description: " "
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/site/" #important: start with /
url: "http://odl.ischool.uw.edu/"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#384452" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#01b2fe"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://twitter.com/ODLiteracy
  - title: medium
    url: https://medium.com/open-data-literacy

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - The Information School
    - University of Washington
    - Seattle, WA 98105
    - odluw@uw.edu
email: odluw@uw.edu
tel: 


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Carole Palmer
    position: Principal Investigator
    text: Carole Palmer is a Professor and Associate Dean for Research at the University of Washington iSchool.
    img: clpalmer.jpg
    social:
      - title: envelope #use for email address
        url: mailto:clpalmer@uw.edu
  - name: Nic Weber
    position: Principal Investigator
    text: Nic Weber is an assistant professor at the University of Washington iSchool.
    img: nWeber.jpg
    social:
      - title: envelope #use for email address
        url: mailto:nmweber@uw.edu
  - name: An Yan
    position: Ph.D. Student
    text: An Yan is currently a Ph.D. student in Information Science at the University of Washington. 
    img: anyan.jpg
    social:
      - title: envelope #use for email address
        url: mailto:yanan15@uw.edu
  - name: Bree Norlander
    position: Project Coordinator
    text: Bree Norlander recently completed her M.L.I.S. at the University of Washington.
    img: bnorlander.jpg
    social:
      - title: envelope #use for email address
        url: mailto:norlab@uw.edu
  - name: Chris Coward
    position: 
    text: Chris Coward is the Co-Founder, Principal Research Scientist, and Director of the Technology & Social Change Group (TASCHA) at the University of Washington Information School. 
    img: ccoward.jpg
    social:
      - title: envelope #use for email address
        url: mailto:ccoward@uw.edu
  - name: Mike Crandall
    position: 
    text: Mike Crandall is a Principal Research Scientist at the University of Washingtonâ€™s Information School.
    img: mikecran.jpg
    social:
      - title: envelope #use for email address
        url: mailto:mikecran@uw.edu
  - name: Bill Howe
    position: 
    text: Bill Howe is an Associate Professor at the University of Washington Information School.
    img: billhowe.jpg
    social:
      - title: envelope #use for email address
        url: mailto:billhowe@uw.edu
  - name: Chris Rothschild
    position: 
    text: Chris is a Research Analyst with the Technology & Social Change Group (TASCHA) at the University of Washington Information School. 
    img: chriskr.jpg
    social:
      - title: envelope #use for email address
        url: mailto:chriskr@uw.edu
  - name: Jevin West
    position: 
    text: Jevin West is an Assistant Professor and Co-Director of the Datalab at the University of Washington Information School.
    img: jevinw.jpg
    social:
      - title: envelope #use for email address
        url: mailto:jevinw@uw.edu



# Clients information. Shown on Home and About pages.
clients:
  - name: Washington State Department of Transportation
    img: wsdot-logo.png
  - name: City of Seattle
    img: CityofSeattle.png
  - name: Seattle Public Library
    img: SPL-Logo.png
  - name: WA Office of the Chief Information Officer
    img: OCIOthumb.png
  - name: WA State Historical Society
    img: wshs-logo.png



# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Open Data Literacy is a collaborative project led by the Information School at the University of Washington in partnership with public institutions that create, manage, and publish open data. Open Data Literacy is funded by a generous grant from the Institute of Museum and Library Services."
# Testimonial content. Shown on Home and About page.
testimonial:
    message: "[Open Data Literacy] will advance data literacy by developing new curriculum for iSchool students and public librarians; coordinating internships, fieldwork, and action research projects between UW and public institutions with open data initiatives, and; producing community workshops and open education resources that are freely available to the general public."
    author: Nic Weber
    position: Assistant Professor @ University of Washington iSchool
